# Generated by Django 2.1.7 on 2019-02-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
