# Generated by Django 2.1.7 on 2019-02-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_publish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='publish',
            new_name='approved',
        ),
    ]
