# Generated by Django 2.1.7 on 2019-02-20 02:16

from django.db import migrations
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190219_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now, verbose_name='Content'),
            preserve_default=False,
        ),
    ]
